name: dev-branch-ci

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
      
      - name: build
        run: |
          $targetFolder = "$($env:RUNNER_TEMP)\ycps"
          mkdir $targetFolder
          dotnet build && dotnet publish --self-contained --use-current-runtime -c Debug -o $targetFolder
        shell: pwsh
      
      - name: push package
        run: |
          $targetFolder = "$($env:RUNNER_TEMP)\ycps"
          Publish-Module -Path $targetFolder -NuGetApiKey ${{ secrets.PS_GALLERY_SECRET }}
        shell: pwsh